#!/bin/bash

cd libshape && wmake
cd ../libmotion && wmake
cd ../libcollision && wmake
cd ../ && wmake

###export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/libmotion
###export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/libshape
###export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/libcollision

